from enum import StrEnum


class ArtifactKind(StrEnum):
    CLI_RESULT = "cli_result"
    INPUT_REQUEST = "input_request"
    DSW_DISCOVERY = "dsw_discovery"
    SOURCE_MEMBERSHIP = "source_membership"
    PROJECT_MEMBERSHIP = "project_membership"
    BUILD_CONTEXT = "build_context"
    SOURCE_DIGEST = "source_digest"
    FUNCTION_LOCATION = "function_location"
    FUNCTION_SIGNATURE = "function_signature"
    GLOBAL_ACCESS = "global_access"
    CALL_REPORT = "call_report"
    COVERAGE_DESIGN = "coverage_design"
    BOUNDARY_CANDIDATES = "boundary_candidates"
    DEPENDENCY_POLICY = "dependency_policy"
    TEST_SPEC = "test_spec"
    HARNESS_SKELETON_REPORT = "harness_skeleton_report"
    BUILD_WORKSPACE_REPORT = "build_workspace_report"
    BUILD_PROBE_REPORT = "build_probe_report"
    BUILD_COMPLETION_PLAN = "build_completion_plan"
    BUILD_COMPLETION_ITERATION = "build_completion_iteration"
    BUILD_COMPLETION_HISTORY = "build_completion_history"
    TEST_EXECUTION_REPORT = "test_execution_report"
    TEST_RESULT = "test_result"
    EVIDENCE_MANIFEST = "evidence_manifest"
    FUNCTION_DOSSIER = "function_dossier"
    DOSSIER_MANIFEST = "dossier_manifest"
    STATE_SETUP_REFLECTION = "state_setup_reflection"
    REVIEW_DECISIONS = "review_decisions"
    CHANGE_IMPACT = "change_impact"
    TEST_CASE_RECONCILIATION = "test_case_reconciliation"
    REGRESSION_SELECTION = "regression_selection"
    REANALYSIS_SNAPSHOT = "reanalysis_snapshot"
    SUITE_MANIFEST = "suite_manifest"
    SUITE_RUN_REPORT = "suite_run_report"
    LATEST_RUN_POINTER = "latest_run_pointer"
    LATEST_EVIDENCE_POINTER = "latest_evidence_pointer"
    LATEST_SUITE_RUN_POINTER = "latest_suite_run_pointer"
    EVIDENCE_SOURCE_RUN = "evidence_source_run"
    PROMPT_PACK = "prompt_pack"
    QUICK_SUMMARY = "quick_summary"


class ContractMode(StrEnum):
    COMPATIBLE = "compatible"
    STRICT = "strict"


class RunOutcome(StrEnum):
    PLANNED = "planned"
    PASSED = "passed"
    FAILED = "failed"
    BLOCKED = "blocked"
    INCONCLUSIVE = "inconclusive"
    CANCELLED = "cancelled"
    TIMED_OUT = "timed_out"
    ERROR = "error"
